sudo: required
services:
  - docker

before_install:
  - docker build -t amitatpug/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true amitatpug/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: " "
  app: "docker-app"
  env: "docker-env"
  bucket_name: " "
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
