sudo: required
services:
  - docker

before_install:
  - docker build -t amitatpug/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true amitatpug/docker-react npm run test -- --coverage
